export const frameworkExamples: Record<string, string> = {
    TypeScript: [
        '// usePapevi.ts — works for Vue, React, Svelte',
        "const BASE = 'https://api.papevi.app/api/v1'",
        'const token = import.meta.env.VITE_PAPEVI_TOKEN',
        '',
        'export function usePapevi() {',
        '  async function get<T>(path: string): Promise<T> {',
        '    const res = await fetch(`${BASE}${path}`, {',
        '      headers: { Authorization: `Bearer ${token}` },',
        '    })',
        '    if (!res.ok) throw new Error(`Papevi ${res.status}`)',
        '    return res.json()',
        '  }',
        '',
        '  return { get }',
        '}',
    ].join('\n'),
    PHP: [
        '<?php',
        'use Illuminate\\Support\\Facades\\Http;',
        '',
        "// config/services.php: 'papevi' => ['token' => env('PAPEVI_TOKEN')]",
        '',
        "$response = Http::withToken(config('services.papevi.token'))",
        "    ->baseUrl('https://api.papevi.app/api/v1')",
        "    ->get('/pages');",
        '',
        "$pages = $response->json('data');",
    ].join('\n'),

    'C#': [
        '// PapeviClient.cs',
        'using System.Net.Http.Headers;',
        'using System.Text.Json;',
        '',
        'public class PapeviClient',
        '{',
        '    private readonly HttpClient _client;',
        '    private const string Base = "https://api.papevi.app/api/v1";',
        '',
        '    public PapeviClient(string token)',
        '    {',
        '        _client = new HttpClient();',
        '        _client.DefaultRequestHeaders.Authorization =',
        '            new AuthenticationHeaderValue("Bearer", token);',
        '    }',
        '',
        '    public async Task<T?> GetAsync<T>(string path)',
        '    {',
        '        var response = await _client.GetAsync($"{Base}{path}");',
        '        response.EnsureSuccessStatusCode();',
        '        return await response.Content.ReadFromJsonAsync<T>();',
        '    }',
        '}',
    ].join('\n'),
};
