export const pagesExamples: Record<string, string> = {
    TypeScript: [
        "import { usePapevi } from './usePapevi'",
        '',
        'interface Page {',
        '  id: string',
        "  type: 'pages'",
        '  attributes: {',
        '    slug: string',
        '    title: string',
        '    body: unknown',
        '    published_at: string',
        '    seo: { meta_title: string; meta_description: string }',
        '  }',
        '}',
        '',
        'const { get } = usePapevi()',
        "const { data: pages } = await get<{ data: Page[] }>('/pages?sort=-created_at')",
        '',
        'for (const page of pages) {',
        '  console.log(page.attributes.title, page.attributes.slug)',
        '}',
    ].join('\n'),

    'Vue 3': [
        '// composables/usePages.ts',
        "import { ref, onMounted } from 'vue'",
        "import { usePapevi } from '@/composables/usePapevi'",
        '',
        'interface Page {',
        '  id: string',
        "  type: 'pages'",
        '  attributes: {',
        '    slug: string',
        '    title: string',
        '    body: unknown',
        '    published_at: string',
        '    seo: { meta_title: string; meta_description: string }',
        '  }',
        '}',
        '',
        'export function usePages() {',
        '  const pages = ref<Page[]>([])',
        '  const { get } = usePapevi()',
        '',
        '  onMounted(async () => {',
        "    const { data } = await get<{ data: Page[] }>('/pages?sort=-created_at')",
        '    pages.value = data',
        '  })',
        '',
        '  return { pages }',
        '}',
        '',
        '// In a component',
        "import { usePages } from '@/composables/usePages'",
        '',
        'const { pages } = usePages()',
    ].join('\n'),

    React: [
        '// hooks/usePages.ts',
        "import { useEffect, useState } from 'react'",
        "import { usePapevi } from '@/hooks/usePapevi'",
        '',
        'interface Page {',
        '  id: string',
        "  type: 'pages'",
        '  attributes: {',
        '    slug: string',
        '    title: string',
        '    body: unknown',
        '    published_at: string',
        '    seo: { meta_title: string; meta_description: string }',
        '  }',
        '}',
        '',
        'export function usePages() {',
        '  const [pages, setPages] = useState<Page[]>([])',
        '  const { get } = usePapevi()',
        '',
        '  useEffect(() => {',
        "    get<{ data: Page[] }>('/pages?sort=-created_at')",
        '      .then(({ data }) => setPages(data))',
        '  }, [])',
        '',
        '  return pages',
        '}',
        '',
        '// components/PostList.tsx',
        "import { usePages } from '@/hooks/usePages'",
        '',
        'export function PostList() {',
        '  const pages = usePages()',
        '  return (',
        '    <ul>',
        '      {pages.map((p) => (',
        '        <li key={p.id}>{p.attributes.title}</li>',
        '      ))}',
        '    </ul>',
        '  )',
        '}',
    ].join('\n'),

    PHP: [
        '<?php',
        'use Illuminate\\Support\\Facades\\Http;',
        '',
        "$response = Http::withToken(config('services.papevi.token'))",
        "    ->baseUrl('https://api.papevi.app/api/v1')",
        "    ->get('/pages', ['sort' => '-created_at']);",
        '',
        "foreach ($response->json('data') as $page) {",
        "    echo $page['attributes']['title'] . ' (' . $page['attributes']['slug'] . ')' . PHP_EOL;",
        '}',
    ].join('\n'),

    'C#': [
        '// Program.cs',
        'var client = new PapeviClient(Environment.GetEnvironmentVariable("PAPEVI_TOKEN")!);',
        '',
        'record PageAttributes(string Slug, string Title);',
        'record Page(string Id, string Type, PageAttributes Attributes);',
        'record PageListResponse(Page[] Data);',
        '',
        'var result = await client.GetAsync<PageListResponse>("/pages?sort=-created_at");',
        '',
        'foreach (var page in result?.Data ?? [])',
        '{',
        '    Console.WriteLine($"{page.Attributes.Title} ({page.Attributes.Slug})");',
        '}',
    ].join('\n'),

    Svelte: [
        '<script lang="ts">',
        "  import { onMount } from 'svelte'",
        "  import { usePapevi } from '$lib/usePapevi'",
        '',
        '  interface Page {',
        '    id: string',
        "    type: 'pages'",
        '    attributes: {',
        '      slug: string',
        '      title: string',
        '      body: unknown',
        '      published_at: string',
        '      seo: { meta_title: string; meta_description: string }',
        '    }',
        '  }',
        '',
        '  let pages: Page[] = []',
        '  const { get } = usePapevi()',
        '',
        '  onMount(async () => {',
        "    const { data } = await get<{ data: Page[] }>('/pages?sort=-created_at')",
        '    pages = data',
        '  })',
        '</script>',
        '',
        '<ul>',
        '  {#each pages as page (page.id)}',
        '    <li>',
        '      <a href="/blog/{page.attributes.slug}">',
        '        {page.attributes.title}',
        '      </a>',
        '    </li>',
        '  {/each}',
        '</ul>',
    ].join('\n'),
};
